### PR TITLE
feat: Add support for tokens BNTY and MKR

### PR DESCRIPTION
**Pull request by vrolland**
This change is [Reviewable](https://reviewable.io/reviews/requestnetwork/requestnetwork-v1-archive/4)

### CODE REVIEW

**Review by lumtis — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/requestnetwork/requestnetwork-v1-archive/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @romaric-juniet)

**Review by romaric-juniet — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/requestnetwork/requestnetwork-v1-archive/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by romaric-juniet — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/requestnetwork/requestnetwork-v1-archive/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lumtis — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/requestnetwork/requestnetwork-v1-archive/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
